### PR TITLE
Moodle updates

### PR DESCRIPTION
**Pull request by hrpatel**
- Move ARGS closer to code that uses it
- Update file and directory to remove read permissions
- Bake in auto enrol plugin
- Update Moove theme version

### CODE REVIEW

**Comment by mroote** [comment]
I think I'd prefer to keep all the args at the top of the file, then you aren't searching through trying to find the one variable to change. Other changes look good to me though.

**Comment by hrpatel** [comment]
The reason I changed their location is to speed up builds.

E.g. Changing `ONELOGIN_PLUGIN_VER` with all the args on the top rebuilds every layer. In the new layout, it only builds layers after `ONELOGIN_PLUGIN_VER`

**Comment by mroote** [comment]
Ah good point, alright lets leave it then.

**Review by mroote — APPROVED** [review]
+1

**Pull request merged**
